server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        # L'IP privée de ton backend
        proxy_pass http://172.31.75.220:5000;
        
        # Supprime les lignes "Upgrade" et "Connection" si tu les avais mises
        # Utilise ces en-têtes standards à la place :
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Force HTTP 1.1 pour éviter l'erreur 426
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}